### ISSUE TITLE
viewing the home_controller is exceptional if pg_stats_statements is installed but pg_query is not in the Gemfile

### ISSUE THREAD

**Issue by treznick** [ankane/pghero#121] opened 2017-08-09 15:47 UTC
This little bit of [`HomeController#index`](https://github.com/ankane/pghero/blob/master/app/controllers/pg_hero/home_controller.rb#L42-L46) will eventually call out to [`PgHero::Methods::SuggestedIndexes#suggested_indexes_by_query`](https://github.com/ankane/pghero/blob/20a2d43f34b5d497433ea09900a4631a13a3ea74/lib/pghero/methods/suggested_indexes.rb#L9-L43), which will raise if `PgQuery` is not available.

This was introduced in 8e9da7e672778c9ae039d4cc7832fa2fb62210f6, which will break if `pg_stats_statements` is available but not if the `pg_query` gem is not installed.

Happy to make a PR to address this. Few options for how to think about this come to mind:

1) Include `pg_hero` as a runtime dependency
2) don't raise if `suggested_indexes_enabled?` is false
3) ask if `PgQuery` is defined and of appropriate gem dependency higher up the chain. That, IMHO, might be the better refactor, as it could be the responsibility of a presenter that encapsulates that bit of the `HomeController#index` method

Let me know what the next steps are. Also happy to produce a failing test to reproduce this if necessary.

**Comment by rubemz** [comment] 2017-08-09 17:05
:+1: specially for `don't raise if suggested_indexes_enabled?` is false. 
Took me a bit to find the root cause on why it was raising

**Comment by ankane** [comment] 2017-08-09 17:12
Hey @treznick and @rubemz, thanks for reporting 👍 

Can you confirm it's fixed on master?

**Closed** 2017-08-09 17:12 UTC

**Comment by rubemz** [comment] 2017-08-09 17:16
@ankane @treznick fixed on master for me.
